plugins {
    id 'com.android.library'
}
apply from: rootProject.file('scripts/publish-1.0.0.gradle')

android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion

    defaultConfig {
        minSdkVersion       rootProject.ext.android.minSdkVersion
        targetSdkVersion    rootProject.ext.android.targetSdkVersion
        versionCode         rootProject.ext.android.versionCode
        versionName         rootProject.ext.android.versionName

        consumerProguardFiles "consumer-rules.pro"
        buildConfigField "int", "VERSION_CODE", "${defaultConfig.versionCode}"
        buildConfigField "String", "VERSION_NAME", "\"${defaultConfig.versionName}\""
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly project(path: ':library')

    //https://github.com/greenrobot/EventBus JPush各种操作&收到消息回调后使用EventBus转发
    compileOnly 'org.greenrobot:eventbus:3.3.1'

    //https://docs.jiguang.cn//jpush/client/Android/android_guide/ 极光推送
    //http://docs.jiguang.cn/jpush/updates/ 最新版本号
    //https://docs.jiguang.cn/jpush/client/Android/android_guide#配置-mavencentral-支持
    compileOnly ('cn.jiguang.sdk:jpush:5.2.2') {    //必选, 注意：5.0.0 版本开始可以自动拉取 JCore 包，无需另外配置
        exclude group: 'cn.jiguang.sdk', module: 'jcore'  //+ JCore 包最新版
    }
//    compileOnly 'cn.jiguang.sdk:jcore:4.5.0'    //可选，JCore 包，if你发现↑自动集成的有问题, 可以使用这个和↑同一天发布的包
//    compileOnly 'cn.jiguang.sdk:joperate:2.0.2' //可选，集成极光分析SDK后，即可支持行为触发推送消息、推送转化率统计，用户行为分析和用户标签等功能

    //JCore
//    compileOnly project(path: ':tempgen') //tempgen已禁止打包, jitpack打包的时候用↓
    compileOnly files('../tempgen/libs/tempgen-2.2.1.jar')
}