apply plugin: 'com.android.library'

apply from: rootProject.file('scripts/publish-1.0.0.gradle')

android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion

    defaultConfig {
        minSdkVersion       rootProject.ext.android.minSdkVersion
        targetSdkVersion    rootProject.ext.android.targetSdkVersion
        versionCode         rootProject.ext.android.versionCode
        versionName         rootProject.ext.android.versionName

        consumerProguardFiles 'consumer-rules.pro'
        buildConfigField "int", "VERSION_CODE", "${defaultConfig.versionCode}"
        buildConfigField "String", "VERSION_NAME", "\"${defaultConfig.versionName}\""

        //增加vector图像支持
        vectorDrawables.useSupportLibrary = true
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    //Android8, 在android节点内添加
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api fileTree(dir: "libs", include: ["*.jar", '*.aar'])

    //ViewPager
    compileOnly rootProject.ext.dependencies.appcompat_appcompat

    //TabLayout
    compileOnly (rootProject.ext.dependencies.material_material) {
        exclude group: 'androidx.appcompat', module: 'appcompat'                //1.1.0
        exclude group: 'androidx.recyclerview', module: 'recyclerview'          //1.1.0
        exclude group: 'androidx.constraintlayout', module: 'constraintlayout'  //2.0.1
    }

    //TODO: compileOnly 不会把 AAR 放入资源合并的输入中，AAPT 在编译你的 library 时，根本“看不到” RecyclerView 定义了哪些属性
    //      所以直接报错“attribute not found”, 找不到 layoutManager 属性
    implementation (rootProject.ext.dependencies.androidx_recyclerview) {
//        exclude group: 'androidx.core', module: 'core'              //1.3.2, androidx.core.view.ScrollingView
        exclude group: 'androidx.customview', module: 'customview'  //1.0.0
    }

    //compileOnly: layout_constraintBottom_toTopOf 属性在本地编译不通过
    implementation rootProject.ext.dependencies.androidx_constraintlayout

    //基础库, compileOnly: ratio 属性在本地编译不通过
    implementation project(path: ':library')
}
