plugins {
    id 'com.android.library'
}
apply from: rootProject.file('scripts/publish-1.0.0.gradle')

android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion

    defaultConfig {
        minSdkVersion       rootProject.ext.android.minSdkVersion
        targetSdkVersion    rootProject.ext.android.targetSdkVersion
        versionCode         rootProject.ext.android.versionCode
        versionName         rootProject.ext.android.versionName

        consumerProguardFiles "consumer-rules.pro"
        buildConfigField "int", "VERSION_CODE", "${defaultConfig.versionCode}"
        buildConfigField "String", "VERSION_NAME", "\"${defaultConfig.versionName}\""
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    //Android8, 在android节点内添加
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    //AppCompatActivity
    // compileOnly: AAPT: error: resource style/Theme.AppCompat.Light.NoActionBar (aka com.actor.picture_selector:style/Theme.AppCompat.Light.NoActionBar) not found.
    implementation rootProject.ext.dependencies.appcompat_appcompat

    compileOnly (rootProject.ext.dependencies.androidx_recyclerview) {
        transitive = false
    }

    //compileOnly 找不到 layout_constraintDimensionRatio
    implementation rootProject.ext.dependencies.androidx_constraintlayout

    //基础库
    compileOnly project(path: ':library')

    //https://github.com/LuckSiege/PictureSelector 选择图片(裁剪,压缩,自定义相机)、视频、音频(minSdkVersion 21)
    api ('io.github.lucksiege:pictureselector:v3.11.2') {
//        transitive = false
        exclude group: 'androidx.appcompat', module: 'appcompat'                //1.3.1
        exclude group: 'androidx.recyclerview', module: 'recyclerview'          //1.2.1
        //排除编译会报错: androidx.activity.result.ActivityResultLauncher
//        exclude group: 'androidx.activity', module: 'activity'                  //1.3.1
        exclude group: 'androidx.fragment', module: 'fragment'                  //1.3.1
        exclude group: 'androidx.exifinterface', module: 'exifinterface'        //1.3.3
        exclude group: 'androidx.viewpager2', module: 'viewpager2'              //1.0.0
        exclude group: 'androidx.constraintlayout', module: 'constraintlayout'  //2.1.4
    }

    // 图片压缩 (按需引入)
    compileOnly 'io.github.lucksiege:compress:v3.11.2'

    // 图片裁剪 (按需引入)
    compileOnly ('io.github.lucksiege:ucrop:v3.11.2') {
        exclude group: 'androidx.appcompat', module: 'appcompat'        //1.3.1
        exclude group: 'androidx.exifinterface', module: 'exifinterface'//1.3.3
        exclude group: 'androidx.transition', module: 'transition'      //1.4.1
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'         //3.12.13
        exclude group: 'androidx.recyclerview', module: 'recyclerview'  //1.2.1
        exclude group: 'com.google.code.gson', module: 'gson'           //2.8.6
    }

    // 自定义相机 (按需引入)
    compileOnly ('io.github.lucksiege:camerax:v3.11.2') {
//        exclude group: 'androidx.camera', module: 'camera-view'         //1.2.1
//        exclude group: 'androidx.camera', module: 'camera-lifecycle'    //1.3.1
//        exclude group: 'androidx.camera', module: 'camera-core'         //1.2.1
//        exclude group: 'androidx.camera', module: 'camera-camera2'      //1.2.1
        exclude group: 'androidx.appcompat', module: 'appcompat'            //1.3.1
        exclude group: 'androidx.transition', module: 'transition'          //1.4.1
        exclude group: 'androidx.concurrent', module: 'concurrent-futures'  //1.1.1
    }
}