// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply from: "config.gradle"

buildscript {
    repositories {
        mavenLocal()
        maven { url 'D://repository' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://developer.huawei.com/repo/' }
        maven { url 'https://repo1.maven.org/maven2/' }
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://jitpack.io' }
        mavenCentral()
        google()
        jcenter()
    }
    dependencies {
        //这就是 AGP( Android Gradle Plugin) 版本，是 Google 官方为 Android 项目开发的 Gradle 插件。它的作用是：编译、打包、资源处理、依赖管理、构建任务
//        classpath 'com.android.tools.build:gradle:4.0.1'
        classpath 'com.android.tools.build:gradle:4.1.2'
//        classpath 'com.android.tools.build:gradle:4.2.2'
//        classpath 'com.android.tools.build:gradle:7.3.1'
//        classpath 'com.android.tools.build:gradle:7.4.2'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.3.0' // add plugin

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()    // 让 Gradle 能在本地 Maven 仓库中查找依赖
        maven { url 'D://repository' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://developer.huawei.com/repo/' }
        maven { url 'https://repo1.maven.org/maven2/' }
        maven { url 'https://www.jitpack.io' }
        maven { url 'https://jitpack.io' }
        mavenCentral()
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
