/**
 * 下载 Gitee 上的 publish-maven.gradle, 用于将 library 打包并发布到本地maven .aar / sourcesJar / javadocJar
 *
 * 1.在 library 的 gradle 的  apply plugin: 'com.android.library'  后面或 plugins{} 后面添加:
 *   apply from: "https://raw.giteeusercontent.com/actor20170211030627/MyAndroidFrameWork/raw/master/scripts/download/publish-maven_download-gitee.gradle"
 *
 * 2.在 gradle.properties 中添加你的 PUBLISH_GROUP_ID, 例:
 *   PUBLISH_GROUP_ID = com.github.actor20170211030627.MyAndroidFrameWork
 *
 * 3.详细使用请查看 scriptNames 这2个文件
 */

//脚本名称
def scriptNames = ["publish-1.0.0.gradle", "publish-maven-1.0.0.gradle"]

def baseUrl = "https://raw.giteeusercontent.com/actor20170211030627/MyAndroidFrameWork/raw/master/scripts"
def localDir = new File(rootProject.projectDir, ".gradle/scripts")
localDir.mkdirs()

scriptNames.each { name ->
    def localFile = new File(localDir, name)
    if (!localFile.exists()) {
        try {
            localFile.text = new URL("${baseUrl}/${name}").getText('UTF-8')
            println("${name} 已下载到: ${localDir.absolutePath}, 使用方法见 ${name} 内说明")
        } catch (Exception e) {
            throw new GradleException("无法下载 ${name}，请检查网络或访问 ${baseUrl}", e)
        }
    } else {
        println "${name} 使用本地缓存: ${localFile.absolutePath}"
    }
}
// 按顺序 apply
apply from: new File(localDir, scriptNames[0])
apply from: new File(localDir, scriptNames[1])