apply plugin: 'com.android.library'

android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion

    defaultConfig {
        minSdkVersion       rootProject.ext.android.minSdkVersion
        targetSdkVersion    rootProject.ext.android.targetSdkVersion
        versionCode 1
        versionName "1.0"

        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

// 禁用所有 variant 的 AAR 打包
android.libraryVariants.all { variant ->
    tasks.named("bundle${variant.name.capitalize()}Aar").configure {
        enabled = false
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar", '*.aar'])

    //https://github.com/greenrobot/greenDAO 数据库
    compileOnly 'org.greenrobot:greendao:3.3.0'
}
