plugins {
    id 'com.android.library'
}
apply from: rootProject.file('scripts/publish-1.0.0.gradle')

android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion

    defaultConfig {
        minSdkVersion       rootProject.ext.android.minSdkVersion
        targetSdkVersion    rootProject.ext.android.targetSdkVersion
        versionCode         rootProject.ext.android.versionCode
        versionName         rootProject.ext.android.versionName

        consumerProguardFiles 'consumer-rules.pro'
        buildConfigField "int", "VERSION_CODE", "${defaultConfig.versionCode}"
        buildConfigField "String", "VERSION_NAME", "\"${defaultConfig.versionName}\""
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    //Android8, 在android节点内添加
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly rootProject.ext.dependencies.androidx_annotation

    //https://github.com/greenrobot/greenDAO 数据库
    compileOnly 'org.greenrobot:greendao:3.3.0'

    //https://github.com/yuweiguocn/GreenDaoUpgradeHelper greenDAO数据库升级
    compileOnly ('io.github.yuweiguocn:GreenDaoUpgradeHelper:v2.2.1') {
        exclude group: 'androidx.annotation', module: 'annotation'  //1.0.0
    }

    //GreenDao数据库
    compileOnly project(path: ':tempgen')
}