plugins {
    id 'com.android.library'
}
apply from: rootProject.file('scripts/publish-1.0.0.gradle')

android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion

    defaultConfig {
        minSdkVersion       rootProject.ext.android.minSdkVersion
        targetSdkVersion    rootProject.ext.android.targetSdkVersion
        versionCode         rootProject.ext.android.versionCode
        versionName         rootProject.ext.android.versionName

        consumerProguardFiles 'consumer-rules.pro'
        buildConfigField "int", "VERSION_CODE", "${defaultConfig.versionCode}"
        buildConfigField "String", "VERSION_NAME", "\"${defaultConfig.versionName}\""
    }

    buildTypes {
        release {
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    //Android8, 在android节点内添加
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    //有注解
    compileOnly rootProject.ext.dependencies.androidx_annotation

    //https://github.com/Blankj/AndroidUtilCode 许多工具
    compileOnly ('com.blankj:utilcodex:1.31.1') {
        transitive = false
    }

    //https://opendocs.alipay.com/open/02no45 支付宝
    //compileOnly 'com.alipay.sdk:alipaysdk-android:+@aar' //直接获取最新版
    compileOnly 'com.alipay.sdk:alipaysdk-android:15.8.17' //指定版本(推荐)
}